package nekr0s.project.card_users.models.enums;

public enum RequestReason {
    REASON_LOST,
    REASON_STOLEN,
    REASON_MALFUNCTIONING,
    REASON_DAMAGED,
    REASON_ADDRESS_CHANGE,
    REASON_NAME_CHANGE,
    REASON_PHOTO_CHANGE,

    //
    REASON_EXPIRED,
    REASON_DUE_TO_EXPIRE,
    REASON_SUSPENDED,
    REASON_WITHDRAWN
}
